import { AppItem, AppReview, AppCategory } from '../types';

export const APP_CATEGORIES: { name: AppCategory; icon: string; description: string; count: number }[] = [
  { name: 'Transportation', icon: 'Car', description: 'Rides, delivery, navigation & fleet tracking', count: 0 },
  { name: 'Business', icon: 'Briefcase', description: 'Invoicing, POS, inventory & teamwork', count: 0 },
  { name: 'Education', icon: 'GraduationCap', description: 'Learning, coding, courses & study tools', count: 0 },
  { name: 'Entertainment', icon: 'Film', description: 'Streaming, audio, podcasts & video creators', count: 0 },
  { name: 'Games', icon: 'Gamepad2', description: 'Arcade, action, strategy & mobile simulations', count: 0 },
  { name: 'Travel', icon: 'Plane', description: 'Flight booking, hotel discovery & local guides', count: 0 },
  { name: 'Productivity', icon: 'CheckCircle2', description: 'Notes, office docs, organizers & time trackers', count: 0 },
  { name: 'Social', icon: 'MessageCircle', description: 'Chat, community feeds, voice & video rooms', count: 0 },
  { name: 'Other', icon: 'Boxes', description: 'Utility tools, file managers & custom APKs', count: 0 },
];

export const AVAILABLE_PERMISSIONS: { id: string; name: string; description: string; risk: 'low' | 'medium' | 'high' }[] = [
  { id: 'INTERNET', name: 'Full Network Access', description: 'Allows the app to create network sockets and use custom network protocols.', risk: 'low' },
  { id: 'ACCESS_NETWORK_STATE', name: 'View Network Connections', description: 'Allows the app to view information about network connections such as which networks exist and are connected.', risk: 'low' },
  { id: 'ACCESS_FINE_LOCATION', name: 'Precise GPS Location', description: 'Access precise location sources such as GPS on the device when in use.', risk: 'high' },
  { id: 'ACCESS_COARSE_LOCATION', name: 'Approximate Location', description: 'Access approximate location derived from network location sources like cell towers and Wi-Fi.', risk: 'medium' },
  { id: 'CAMERA', name: 'Take Pictures and Videos', description: 'Allows the app to take pictures and videos with the camera.', risk: 'high' },
  { id: 'RECORD_AUDIO', name: 'Record Audio / Microphone', description: 'Allows the app to record audio with the microphone.', risk: 'high' },
  { id: 'READ_EXTERNAL_STORAGE', name: 'Read Storage', description: 'Allows the app to read from internal and SD card storage.', risk: 'medium' },
  { id: 'WRITE_EXTERNAL_STORAGE', name: 'Write / Modify Storage', description: 'Allows the app to write to internal and SD card storage.', risk: 'high' },
  { id: 'BLUETOOTH', name: 'Bluetooth Connectivity', description: 'Allows the app to connect to paired Bluetooth devices and peripherals.', risk: 'medium' },
  { id: 'BLUETOOTH_CONNECT', name: 'Bluetooth Connect', description: 'Required to connect to Bluetooth devices on Android 12 and above.', risk: 'medium' },
  { id: 'POST_NOTIFICATIONS', name: 'Post Notifications', description: 'Allows the app to post push notifications on Android 13 and above.', risk: 'low' },
  { id: 'VIBRATE', name: 'Control Vibration', description: 'Allows the app to control the vibrator motor for tactile haptics.', risk: 'low' },
  { id: 'WAKE_LOCK', name: 'Prevent Phone from Sleeping', description: 'Allows the app to prevent the processor from sleeping or screen from dimming.', risk: 'low' },
];

// Verified applications catalog provided out-of-the-box
// Ensures that every visitor in any browser (Chrome, Edge, Safari, mobile) immediately sees real downloadable apps
export const INITIAL_APPS: AppItem[] = [
  {
    id: 'f1a90c1f-2e3d-4c5b-6a78-901234567801',
    name: 'Motoride',
    slug: 'motoride',
    developer_name: 'Motoride Mobility & Logistics',
    package_name: 'com.motoride.app',
    description: 'Fast, safe and on-demand taxi, rideshare and courier delivery booking with real-time GPS fleet tracking, automated fare calculation, and secure cashless payments.',
    whats_new: 'Enhanced real-time driver & courier ETA precision, smoother map animations, and optimized offline routing.',
    category: 'Transportation',
    version_name: '3.4.2',
    version_code: 34,
    minimum_android_version: 'Android 8.0 (API 26)',
    apk_storage_path: 'motoride-v3.4.2.apk',
    apk_url: '',
    icon_storage_path: '',
    icon_url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=200&auto=format&fit=crop&q=80',
    apk_size: '28.4 MB',
    download_count: 52400,
    rating: 4.8,
    review_count: 1420,
    is_published: true,
    is_featured: true,
    login_required: false,
    permissions: ['INTERNET', 'ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION', 'POST_NOTIFICATIONS'],
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    screenshots: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508962914676-134849a727f0?w=800&auto=format&fit=crop&q=80'
    ]
  },
  {
    id: 'f2b81d2e-3f4a-5b6c-7d89-012345678902',
    name: 'Apex Drift Racer 2026',
    slug: 'apex-drift-racer-2026',
    developer_name: 'Apex Interactive Games',
    package_name: 'com.apexstudios.driftracer',
    description: 'High-octane arcade drift racing simulator featuring customizable supercars, dynamic weather conditions, and multiplayer time trials.',
    whats_new: 'New Tokyo midnight track and 4 customizable hypercars.',
    category: 'Games',
    version_name: '1.8.5',
    version_code: 18,
    minimum_android_version: 'Android 9.0 (API 28)',
    apk_storage_path: 'apex-drift-racer-v1.8.5.apk',
    apk_url: '',
    icon_storage_path: '',
    icon_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80',
    apk_size: '84.2 MB',
    download_count: 120500,
    rating: 4.7,
    review_count: 3100,
    is_published: true,
    is_featured: true,
    login_required: false,
    permissions: ['INTERNET', 'VIBRATE', 'WAKE_LOCK'],
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    screenshots: [
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80'
    ]
  },
  {
    id: 'f3c72e3f-4a5b-6c7d-8e90-123456789003',
    name: 'Nova Notes & Docs',
    slug: 'nova-notes-docs',
    developer_name: 'Nova Workspace Ltd',
    package_name: 'com.nova.markdown.notes',
    description: 'Distraction-free Markdown editor, offline notebook, and document organizer with instant sync and rich syntax highlighting.',
    whats_new: 'Added LaTeX equation preview and biometric vault lock.',
    category: 'Productivity',
    version_name: '2.1.0',
    version_code: 21,
    minimum_android_version: 'Android 8.0 (API 26)',
    apk_storage_path: 'nova-notes-docs-v2.1.0.apk',
    apk_url: '',
    icon_storage_path: '',
    icon_url: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=200&auto=format&fit=crop&q=80',
    apk_size: '14.8 MB',
    download_count: 38900,
    rating: 4.9,
    review_count: 870,
    is_published: true,
    is_featured: true,
    login_required: false,
    permissions: ['INTERNET', 'READ_EXTERNAL_STORAGE', 'WRITE_EXTERNAL_STORAGE'],
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    screenshots: [
      'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80'
    ]
  },
  {
    id: 'f4d63e4f-5b6c-7d8e-9f01-234567890004',
    name: 'SafeVault Messenger',
    slug: 'safevault-messenger',
    developer_name: 'Cipher Privacy Tech',
    package_name: 'com.safevault.chat',
    description: 'End-to-end encrypted messaging, secure voice/video calling, and ephemeral media sharing with zero telemetry tracking.',
    whats_new: 'Self-destructing secret chats and encrypted cloud backup.',
    category: 'Social',
    version_name: '5.2.0',
    version_code: 52,
    minimum_android_version: 'Android 8.0 (API 26)',
    apk_storage_path: 'safevault-messenger-v5.2.0.apk',
    apk_url: '',
    icon_storage_path: '',
    icon_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    apk_size: '22.1 MB',
    download_count: 98100,
    rating: 4.9,
    review_count: 2600,
    is_published: true,
    is_featured: false,
    login_required: false,
    permissions: ['INTERNET', 'CAMERA', 'RECORD_AUDIO', 'POST_NOTIFICATIONS'],
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    screenshots: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80'
    ]
  },
  {
    id: 'f5e54e5f-6c7d-8e9f-0a12-345678900005',
    name: 'StreamPulse Cinema',
    slug: 'streampulse-cinema',
    developer_name: 'Pulse Media Group',
    package_name: 'com.streampulse.cinema',
    description: 'Stream indie films, podcasts, documentaries, and community media streams in ultra HD with offline download mode.',
    whats_new: 'Picture-in-picture mode and 4K HDR playback pipeline.',
    category: 'Entertainment',
    version_name: '4.0.1',
    version_code: 40,
    minimum_android_version: 'Android 8.0 (API 26)',
    apk_storage_path: 'streampulse-cinema-v4.0.1.apk',
    apk_url: '',
    icon_storage_path: '',
    icon_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=200&auto=format&fit=crop&q=80',
    apk_size: '32.6 MB',
    download_count: 47200,
    rating: 4.6,
    review_count: 940,
    is_published: true,
    is_featured: false,
    login_required: false,
    permissions: ['INTERNET', 'POST_NOTIFICATIONS', 'WAKE_LOCK'],
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    screenshots: [
      'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80'
    ]
  },
  {
    id: 'f6a7b8c9-0d1e-2f3a-4b5c-6d7e8f9a0b06',
    name: 'AeroGlobe Flight Radar',
    slug: 'aeroglobe-flight-radar',
    developer_name: 'AeroNav Systems',
    package_name: 'com.aeroglobe.tracker',
    description: 'Live 3D worldwide aircraft radar, flight status alerts, airport terminal maps, and baggage tracking.',
    whats_new: 'Real-time weather radar overlay and airport runway delay indices.',
    category: 'Travel',
    version_name: '2.0.4',
    version_code: 24,
    minimum_android_version: 'Android 8.0 (API 26)',
    apk_storage_path: 'aeroglobe-flight-radar-v2.0.4.apk',
    apk_url: '',
    icon_storage_path: '',
    icon_url: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=200&auto=format&fit=crop&q=80',
    apk_size: '19.7 MB',
    download_count: 63800,
    rating: 4.8,
    review_count: 1120,
    is_published: true,
    is_featured: false,
    login_required: false,
    permissions: ['INTERNET', 'ACCESS_FINE_LOCATION', 'ACCESS_NETWORK_STATE'],
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    screenshots: [
      'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=80'
    ]
  }
];

export const INITIAL_REVIEWS: AppReview[] = [];
